# -*- Makefile -*-

ccflags-y := -std=gnu89 -g -Wall
ldflags-y := -T$(M)/linkerscript.ld

obj-m += procmon.o

procmon-y += 	syshijack.o                    \
				utils.o                        \
				hookfns.o                      \
				control.o                      \
				syscalls/read.o

$(obj)/syshijack.o: $(obj)/unistd_32.h

$(obj)/unistd_32.h: $(src)/unistd_32_hack.h FORCE
	@cpp $(c_flags) -E -dM <$< | perl -lne 'print if s/^#define __NR_/#define __NR32_/' >$@
