# -*- Makefile -*-

obj-m += procmon.o

procmon-y += syshijack.o hookfns.o utils.o

$(obj)/syshijack.o: $(obj)/unistd_32.h

$(obj)/unistd_32.h: $(src)/unistd_32_hack.h FORCE
	cpp $(c_flags) -E -dM <$< | perl -lne 'print if s/^#define __NR_/#define __NR32_/' >$@
