#############################################################################
# Makefile for building: procmon
# Generated by qmake (2.01a) (Qt 4.8.4) on: Sun May 5 22:45:16 2013
# Project:  procmon.pro
# Template: subdirs
# Command: /usr/lib/qt4/bin/qmake -o Makefile procmon.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/lib/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-lkm_loader \
		sub-procmon

lkm_loader/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) lkm_loader/ || $(MKDIR) lkm_loader/ 
	cd lkm_loader/ && $(QMAKE) /media/HDD/Proyectos/procmon/lkm_loader/lkm_loader.pro -o $(MAKEFILE)
sub-lkm_loader-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) lkm_loader/ || $(MKDIR) lkm_loader/ 
	cd lkm_loader/ && $(QMAKE) /media/HDD/Proyectos/procmon/lkm_loader/lkm_loader.pro -o $(MAKEFILE)
sub-lkm_loader: lkm_loader/$(MAKEFILE) FORCE
	cd lkm_loader/ && $(MAKE) -f $(MAKEFILE)
sub-lkm_loader-make_default-ordered: lkm_loader/$(MAKEFILE) FORCE
	cd lkm_loader/ && $(MAKE) -f $(MAKEFILE) 
sub-lkm_loader-make_default: lkm_loader/$(MAKEFILE) FORCE
	cd lkm_loader/ && $(MAKE) -f $(MAKEFILE) 
sub-lkm_loader-make_first-ordered: lkm_loader/$(MAKEFILE) FORCE
	cd lkm_loader/ && $(MAKE) -f $(MAKEFILE) first
sub-lkm_loader-make_first: lkm_loader/$(MAKEFILE) FORCE
	cd lkm_loader/ && $(MAKE) -f $(MAKEFILE) first
sub-lkm_loader-all-ordered: lkm_loader/$(MAKEFILE) FORCE
	cd lkm_loader/ && $(MAKE) -f $(MAKEFILE) all
sub-lkm_loader-all: lkm_loader/$(MAKEFILE) FORCE
	cd lkm_loader/ && $(MAKE) -f $(MAKEFILE) all
sub-lkm_loader-clean-ordered: lkm_loader/$(MAKEFILE) FORCE
	cd lkm_loader/ && $(MAKE) -f $(MAKEFILE) clean
sub-lkm_loader-clean: lkm_loader/$(MAKEFILE) FORCE
	cd lkm_loader/ && $(MAKE) -f $(MAKEFILE) clean
sub-lkm_loader-distclean-ordered: lkm_loader/$(MAKEFILE) FORCE
	cd lkm_loader/ && $(MAKE) -f $(MAKEFILE) distclean
sub-lkm_loader-distclean: lkm_loader/$(MAKEFILE) FORCE
	cd lkm_loader/ && $(MAKE) -f $(MAKEFILE) distclean
sub-lkm_loader-install_subtargets-ordered: lkm_loader/$(MAKEFILE) FORCE
	cd lkm_loader/ && $(MAKE) -f $(MAKEFILE) install
sub-lkm_loader-install_subtargets: lkm_loader/$(MAKEFILE) FORCE
	cd lkm_loader/ && $(MAKE) -f $(MAKEFILE) install
sub-lkm_loader-uninstall_subtargets-ordered: lkm_loader/$(MAKEFILE) FORCE
	cd lkm_loader/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-lkm_loader-uninstall_subtargets: lkm_loader/$(MAKEFILE) FORCE
	cd lkm_loader/ && $(MAKE) -f $(MAKEFILE) uninstall
procmon/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) procmon/ || $(MKDIR) procmon/ 
	cd procmon/ && $(QMAKE) /media/HDD/Proyectos/procmon/procmon/procmon.pro -o $(MAKEFILE)
sub-procmon-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) procmon/ || $(MKDIR) procmon/ 
	cd procmon/ && $(QMAKE) /media/HDD/Proyectos/procmon/procmon/procmon.pro -o $(MAKEFILE)
sub-procmon: procmon/$(MAKEFILE) FORCE
	cd procmon/ && $(MAKE) -f $(MAKEFILE)
sub-procmon-make_default-ordered: procmon/$(MAKEFILE) sub-lkm_loader-make_default-ordered  FORCE
	cd procmon/ && $(MAKE) -f $(MAKEFILE) 
sub-procmon-make_default: procmon/$(MAKEFILE) FORCE
	cd procmon/ && $(MAKE) -f $(MAKEFILE) 
sub-procmon-make_first-ordered: procmon/$(MAKEFILE) sub-lkm_loader-make_first-ordered  FORCE
	cd procmon/ && $(MAKE) -f $(MAKEFILE) first
sub-procmon-make_first: procmon/$(MAKEFILE) FORCE
	cd procmon/ && $(MAKE) -f $(MAKEFILE) first
sub-procmon-all-ordered: procmon/$(MAKEFILE) sub-lkm_loader-all-ordered  FORCE
	cd procmon/ && $(MAKE) -f $(MAKEFILE) all
sub-procmon-all: procmon/$(MAKEFILE) FORCE
	cd procmon/ && $(MAKE) -f $(MAKEFILE) all
sub-procmon-clean-ordered: procmon/$(MAKEFILE) sub-lkm_loader-clean-ordered  FORCE
	cd procmon/ && $(MAKE) -f $(MAKEFILE) clean
sub-procmon-clean: procmon/$(MAKEFILE) FORCE
	cd procmon/ && $(MAKE) -f $(MAKEFILE) clean
sub-procmon-distclean-ordered: procmon/$(MAKEFILE) sub-lkm_loader-distclean-ordered  FORCE
	cd procmon/ && $(MAKE) -f $(MAKEFILE) distclean
sub-procmon-distclean: procmon/$(MAKEFILE) FORCE
	cd procmon/ && $(MAKE) -f $(MAKEFILE) distclean
sub-procmon-install_subtargets-ordered: procmon/$(MAKEFILE) sub-lkm_loader-install_subtargets-ordered  FORCE
	cd procmon/ && $(MAKE) -f $(MAKEFILE) install
sub-procmon-install_subtargets: procmon/$(MAKEFILE) FORCE
	cd procmon/ && $(MAKE) -f $(MAKEFILE) install
sub-procmon-uninstall_subtargets-ordered: procmon/$(MAKEFILE) sub-lkm_loader-uninstall_subtargets-ordered  FORCE
	cd procmon/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-procmon-uninstall_subtargets: procmon/$(MAKEFILE) FORCE
	cd procmon/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: procmon.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile procmon.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile procmon.pro

qmake_all: sub-lkm_loader-qmake_all sub-procmon-qmake_all FORCE

make_default: sub-lkm_loader-make_default-ordered sub-procmon-make_default-ordered FORCE
make_first: sub-lkm_loader-make_first-ordered sub-procmon-make_first-ordered FORCE
all: sub-lkm_loader-all-ordered sub-procmon-all-ordered FORCE
clean: sub-lkm_loader-clean-ordered sub-procmon-clean-ordered FORCE
distclean: sub-lkm_loader-distclean-ordered sub-procmon-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-lkm_loader-install_subtargets-ordered sub-procmon-install_subtargets-ordered FORCE
uninstall_subtargets: sub-lkm_loader-uninstall_subtargets-ordered sub-procmon-uninstall_subtargets-ordered FORCE

sub-lkm_loader-check_ordered: lkm_loader/$(MAKEFILE)
	cd lkm_loader/ && $(MAKE) -f $(MAKEFILE) check
sub-procmon-check_ordered: procmon/$(MAKEFILE) sub-lkm_loader-check_ordered 
	cd procmon/ && $(MAKE) -f $(MAKEFILE) check
check: sub-lkm_loader-check_ordered sub-procmon-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install_app: FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/media/HDD/Proyectos/procmon/ || $(MKDIR) $(INSTALL_ROOT)/media/HDD/Proyectos/procmon/ 
	-$(INSTALL_PROGRAM) /media/HDD/Proyectos/procmon/procmon/procmon $(INSTALL_ROOT)/media/HDD/Proyectos/procmon/
	-strip $(INSTALL_ROOT)/media/HDD/Proyectos/procmon/procmon


uninstall_app:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/media/HDD/Proyectos/procmon/procmon
	-$(DEL_DIR) $(INSTALL_ROOT)/media/HDD/Proyectos/procmon/ 


install: install_subtargets install_app  FORCE

uninstall: uninstall_app  uninstall_subtargets FORCE

FORCE:

