/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -c ProcmonIface -p procmoniface.h:procmoniface.cpp com.alexandernst.procmon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef PROCMONIFACE_H_1367450349
#define PROCMONIFACE_H_1367450349

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.alexandernst.procmon
 */
class ProcmonIface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.alexandernst.procmon"; }

public:
    ProcmonIface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ProcmonIface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> add_syscall_data(const QString &test)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(test);
        return asyncCallWithArgumentList(QLatin1String("add_syscall_data"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace alexandernst {
    typedef ::ProcmonIface procmon;
  }
}
#endif
